site_name: Książka Kucharska
site_description: Prywatna kolekcja przepisów

theme:
  name: material
  language: pl
  palette:
    primary: deep orange
    accent: amber

plugins:
  - search
  - gen-files:
      scripts:
	    - gen_index.py
  - awesome-pages:
      collapse_single_pages: false

